In [1]:
import numpy as np

# 1. Introducción a Numpy

Numpy (Numerical Python) es una libreria de python que se usa en ciencia de datos. Introduce el concepto de nparray es una estructura de datos mucho más eficiente que las listas nativas de python, sobre todo para trabajar con datos numéricos

## ¿Por qué NumPy en lugar de listas nativas?

Las lista nativas son flexible pero muy lentas se trabaja elemento a elemento. No estan pensandas y optimizadas para calculos matematicos. Numpy almacena datos siempre del mismo tipo (siempre numericos). Permite operaciones vectorizadas mucho mas rapidas.

In [3]:
import time

# sumar de 1 millón de elementos de una lista python
lista = list(range(1_000_000))
inicio = time.time()
resultado = [ x * 2 for x in lista ]
print('tiempo',  time.time() - inicio, sum(resultado))

tiempo 0.07199501991271973 999999000000


In [4]:
# la misma operacion pero con numpy
array = np.arange(1_000_000)
inicio = time.time()
resultado = array * 2
print('tiempo', time.time() - inicio)

tiempo 0.016266345977783203


# El objeto ndarray

Un `ndarray` es un array N-dimensional de elementos del **mismo tipo**. A diferencia de una lista, todos sus elementos ocupan el mismo espacio en memoria, lo que permite operaciones vectorizadas sin bucles explícitos.

In [9]:
np_lista = np.array([10, 20, 30, 40, 50])
print(np_lista)
print(type(np_lista))

# puedo saber el tipo de todos los datos de mi array
print((np_lista.dtype))

np_dobles = np_lista * 2
print(np_dobles)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64
[ 20  40  60  80 100]


In [10]:
booleanos = np.array([1,0,1,0,1,0], dtype=bool)
print(booleanos)
print(booleanos.dtype)

[ True False  True False  True False]
bool


# creacion de arrays con numpy

numpy ofrece multiples formas de crear arrays, desde datos ya existentes (lista, tuplas, ficheros) o mediantes funciones generadoras.



In [14]:
# Vector de zeros
zero_vector = np.zeros(4) # un registro con 3 ceros
print(zero_vector)

# matriz de ceros 4x3 => 2x3 ....
matriz_ceros = np.zeros((4, 3)) # 4 filas y 3 columnas
print(matriz_ceros)

# matriz de unos
matriz_unos = np.ones((2,3))
print(matriz_unos)

# matriz de cualquier valor
matriz_7 = np.full((3,3), 7)
print(matriz_7)

print('-'*30)
# matriz identidad
identidad = np.eye(4)
print(identidad)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# creacion de arrays aleatorios

son imprescindibles para hacer simulaciones, inicializacion de pesos en machine learning, pruebas, etc...

semilla/seet: fija la aleatoriedad de los numeros dentro de  mi array o vector, cuanto mas grande sea el numero mayor aleatoriedad ( seed 0-100)

In [21]:
# fijar la semilla
np.random.seed(45) # fija la aleatoriedad para obtener siempre los mismos valores
alturas = np.round(np.random.uniform(1.40, 2.16, size=10), 2)
print(alturas)

[2.15 1.82 1.61 1.46 1.74 1.76 1.44 1.52 1.49 1.88]
