In [9]:
import numpy as np

# propiedades y estructuras

antes de operar con un array, es fundamental saber como está organizado:
    - cuantas dimensiones tiene
    - que forma
    - cuantos elementos
    - de que tipo

numpy expone todos estos datos a traves de atributos ndarray

In [ ]:
array = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]])
print(array)
print('dimension', array.shape)
print('numero de dimensiones', array.ndim)
print('tipo de dato de los elementos de la array', array.dtype)
print('numero total de elementos', array.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
dimension (4, 3)
numero de dimensiones 2
tipo de dato de los elementos de la array int64
numero total de elementos 12


# RESHAPE: cambiar forma sin cambiar los datos

In [ ]:
vector = np.arange(12)
print(vector)

matriz = vector.reshape(3,4)
print(matriz)

matriz2 = vector.reshape(2,2,3)
print(matriz2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### vista vs copia

In [16]:
original = np.array([1,2,3,4,5,6,7])

vista = original.reshape(1,7)
copia = original.copy()



original[0] = 99

print(original)
print(vista)
print(copia)

float = original.astype(np.float64)
print(float)

[99  2  3  4  5  6  7]
[[99  2  3  4  5  6  7]]
[1 2 3 4 5 6 7]
[99.  2.  3.  4.  5.  6.  7.]
