# EDA 01 — Análisis de notas de la clase 🎓

**Temas que practicamos:** NumPy 01 al 05 (arrays, creación, propiedades, indexación, operaciones)

---

## Contexto

Eres el profesor de matemáticas de 1º de Bachillerato.  
Tienes las **notas del examen de 25 alumnos** (escala 0–10) y quieres analizarlas con NumPy.

El array ya está preparado para que puedas empezar directamente:

In [2]:
import numpy as np

np.random.seed(42)  # fija la aleatoriedad para obtener siempre los mismos valores
notas = np.round(np.random.uniform(2, 10, size=25), 1)
print("Notas de la clase:", notas)

Notas de la clase: [5.  9.6 7.9 6.8 3.2 3.2 2.5 8.9 6.8 7.7 2.2 9.8 8.7 3.7 3.5 3.5 4.4 6.2
 5.5 4.3 6.9 3.1 4.3 4.9 5.6]


In [3]:
import pandas as pd


---
## Ejercicio 1 — Conoce tu array

Muestra por pantalla:
- El número total de alumnos
- El tipo de dato del array
- El número de dimensiones

In [4]:
print('total de alumnos ', notas.size)
print('tipo de dato ', notas.dtype)
print('dimensiones ', notas.ndim)


total de alumnos  25
tipo de dato  float64
dimensiones  1


---
## Ejercicio 2 — Slicing

Muestra las notas del **alumno 5 al alumno 10** (posiciones 4 a 9, recuerda que Python empieza en 0).

In [20]:
print(notas[4:10])


[3.2 3.2 2.5 8.9 6.8 7.7]


---
## Ejercicio 3 — Nota más alta, más baja y media

Calcula con NumPy:
- La nota más alta
- La nota más baja
- La nota media de la clase

> Pista: usa `np.max()`, `np.min()` y `np.mean()`

In [23]:
max = np.max(notas)
min = np.min(notas)
media = np.mean(notas)

print('nota mas alta ', np.max(notas))
print('nota mas baja', np.min(notas))
print('nota media', np.mean(notas))


nota mas alta  9.8
nota mas baja 2.2
nota media 5.528


---
## Ejercicio 4 — Filtrado booleano: aprobados

Crea un array que contenga **solo las notas de los alumnos que han aprobado** (nota >= 5).  
Muestra también cuántos alumnos han aprobado.

In [24]:
aprobados = notas >= 5
print(notas[aprobados])

cantidad = np.sum(aprobados)
print(f' {cantidad} de {len(notas)} aprobados')


[5.  9.6 7.9 6.8 8.9 6.8 7.7 9.8 8.7 6.2 5.5 6.9 5.6]
 13 de 25 aprobados


---
## Ejercicio 5 — Operación vectorial: cambio de escala

El director del centro quiere las notas en escala **0–100** (en lugar de 0–10).  
Convierte todo el array multiplicando cada nota por 10.  
Guarda el resultado en una variable llamada `notas_100`.

In [30]:
notas_100 = np.int64(notas * 10)
print(notas_100)


[50 96 79 68 32 32 25 89 68 77 22 98 87 37 35 35 44 62 55 43 69 31 43 49
 56]


---
## Ejercicio 6 — ¿Cuántos superan la media?

Usando el array original `notas` (escala 0–10), calcula cuántos alumnos tienen una nota **estrictamente superior a la media** de la clase.

In [32]:
alumnos_sobre_media = notas[notas > media]
print(len(alumnos_sobre_media))

lista_aprobados = notas > media
print(np.sum(lista_aprobados))


11
11


---
## Ejercicio 7 — Suspensos

Crea un array `suspensos` con las notas de los alumnos que NO han aprobado (nota < 5).  
Muestra cuántos son y sus notas.

In [28]:
suspensos = notas[notas < 5]
print(suspensos)
print('suspenden ', np.sum(notas < 5), 'sus notas son: ', notas[notas < 5]) 

[3.2 3.2 2.5 2.2 3.7 3.5 3.5 4.4 4.3 3.1 4.3 4.9]
suspenden  12 sus notas son:  [3.2 3.2 2.5 2.2 3.7 3.5 3.5 4.4 4.3 3.1 4.3 4.9]


---
## Ejercicio 8 — np.where: etiquetas

Usa `np.where()` para crear un array de texto donde:
- Si nota >= 5 → `"Aprobado"`
- Si nota < 5 → `"Suspenso"`

Muestra el resultado junto a las notas originales.

In [ ]:
etiquetas = np.where(notas >= 5, 'aprobado', 'suspenso')
for nota, e in zip(notas, etiquetas):
    print(aprobados)


['aprobado' 'aprobado' 'aprobado' 'aprobado' 'suspenso' 'suspenso'
 'suspenso' 'aprobado' 'aprobado' 'aprobado' 'suspenso' 'aprobado'
 'aprobado' 'suspenso' 'suspenso' 'suspenso' 'suspenso' 'aprobado'
 'aprobado' 'suspenso' 'aprobado' 'suspenso' 'suspenso' 'suspenso'
 'aprobado']


---
**Resumen del tema:**

| Concepto | Fórmula | `numpy` | Para qué sirve |
|----------|---------|---------|----------------|
| Media | $\bar{x} = \frac{\sum x_i}{n}$ | `np.mean()` | Valor central típico |
| Mediana | valor del medio ordenado | `np.median()` | Centro robusto (no le afectan extremos) |
| Varianza | $\frac{\sum(x_i-\bar{x})^2}{n}$ | `np.var()` | Dispersión (en unidades²) |
| Desv. típica | $\sqrt{\text{Varianza}}$ | `np.std()` | Dispersión (en mismas unidades) |
| Mínimo/Máximo | — | `np.min()` / `np.max()` | Extremos del conjunto |
| Rango | max − min | `np.ptp()` | Amplitud total |
| Percentil P | valor bajo el que cae el P% | `np.percentile(a, P)` | Posición relativa |
| IQR | Q3 − Q1 | `np.percentile(a,75) - np.percentile(a,25)` | Dispersión central |
| Suma acumulada | — | `np.cumsum()` | Totales acumulados |
| `axis=0` | opera por columnas (↓) | `np.mean(a, axis=0)` | Resumir cada columna |
| `axis=1` | opera por filas (→) | `np.mean(a, axis=1)` | Resumir cada fila |