# Manipulación de arrays

En el trabajo real los datos no siempre llegan en el formato esperado o necesitado. A veces tenemos que **unir** o **dividir** los datos en partes. Y tambien **ordenarlos**

In [1]:
import numpy as np

## Concatenar arrays: Unir dos o mas arrays en uno solo

concatenar dos lista.

In [2]:
grupo_manana = np.array(['Lucia', 'Marta', 'Rodrigo'])
grupo_tarde = np.array(['Juan', 'Lara', 'David'])

todos = np.concatenate([grupo_manana, grupo_tarde])
print(grupo_manana)
print(grupo_tarde)
print(todos)

['Lucia' 'Marta' 'Rodrigo']
['Juan' 'Lara' 'David']
['Lucia' 'Marta' 'Rodrigo' 'Juan' 'Lara' 'David']


En arrays 2D (tablas) tienes dos opciones:
- Pegar **por debajo** (añadir filas): como añadir nuevas filas a una tabla
- Pegar **por la derecha** (añadir columnas): como añadir nuevas columnas a una tabla

```
Pegar por debajo (axis=0):      Pegar por la derecha (axis=1):

[1, 2]          [1, 2, 5, 6]
[3, 4]  +        →
[5, 6]          [3, 4, 7, 8]
[7, 8]
```

In [3]:
# concatenar tablas de 2D
# imagina que tienes las notas de clase por aula

clase_A = np.array([
    [6,7,8], # 1 alumno de A
    [2,7,4]  # 2 alumno de A
])

clase_B = np.array([
    [8,6,8], # 1 alumno de B
    [4,9,6], # 2 alumno de B
    [7,7,5]  # 3 alumno de B
])

# poner todas las notas de las dos clases juntas en axis=0 pegar hacia abajo
todas_las_clases = np.concatenate([clase_A, clase_B], axis=0)
print(todas_las_clases)
print('dimensión array resultante 5 alumnos 3 asignaturas')
print(todas_las_clases.shape)

[[6 7 8]
 [2 7 4]
 [8 6 8]
 [4 9 6]
 [7 7 5]]
dimensión array resultante 5 alumnos 3 asignaturas
(5, 3)


In [4]:
# imagina que quieres las notas por asignatura
# necesito las notas por asignatura

notas_mates = np.array([ [6], [7] , [10] ]) # 3 alumnos 1 columna
notas_ingles = np.array([ [2], [4] , [7] ]) # 3 alumnos 1 columna
notas_ciencias = np.array([ [2], [4] , [7] ])

# axis = 1 añadir por columnas poner una al lado de la otra
tabla = np.concatenate([notas_mates, notas_ingles, notas_ciencias], axis=1)
print(tabla)


[[ 6  2  2]
 [ 7  4  4]
 [10  7  7]]


## vstack y hstack atajos de apilación

vstack => vertical
hstack => horizontal

```
vstack  →  apila en vertical (uno encima del otro):
           [1, 2, 3]        [[1, 2, 3],
           [4, 5, 6]   →    [4, 5, 6]]

hstack  →  apila en horizontal (uno al lado del otro):
           [1, 2] y [3, 4]  →  [1, 2, 3, 4]
```


In [5]:
primer_trimestre = np.array([7,6,5,4,3,2,1])
segundo_trimestre = np.array([1,3,5,7,9,11,13])

# vstack los vectores pasan a ser filas de la matriz
notas_2_trimestres = np.vstack([primer_trimestre, segundo_trimestre])
print(notas_2_trimestres)
print(notas_2_trimestres.shape, '2 trimestres 7 alumnos')

# hstack los vectores se concatenan un vector con todas las notas.
todo_junto = np.hstack([primer_trimestre, segundo_trimestre])
print(todo_junto)

[[ 7  6  5  4  3  2  1]
 [ 1  3  5  7  9 11 13]]
(2, 7) 2 trimestres 7 alumnos
[ 7  6  5  4  3  2  1  1  3  5  7  9 11 13]


---
##  Dividir arrays: la operación inversa

Dividir es lo contrario de concatenar: **partir un array en trozos**.

```
Array original: [10, 20, 30, 40, 50, 60]

Dividido en 3 partes iguales:
  Parte 1: [10, 20]
  Parte 2: [30, 40]
  Parte 3: [50, 60]
```

También puedes indicar **en qué posiciones** se hacen los cortes:

```
Array: [10, 20, 30, 40, 50, 60, 70, 80]
Cortes en posición 3 y 6:
         [10, 20, 30] | [40, 50, 60] | [70, 80]
                       ↑             ↑
                    pos 3           pos 6
```



In [6]:
notas_todos = np.array([6.5 ,4.3 ,7 ,1.5 ,0 ,9 ,10 ,7.5 ,8 ,8.7 ,4, 5])

# dividir en 3 grupos iguales ( divisible exacto )
grupo1, grupo2, grupo3, grupo4 = np.split(notas_todos, 4)
print( grupo1 )
print( grupo2 )
print( grupo3 )
print( grupo4 )

print('=' * 30)
# dividir en posiciones especificas.

inicio, medio, fin = np.split(notas_todos, [4, 10])
print(inicio)
print(medio)
print(fin)


[6.5 4.3 7. ]
[1.5 0.  9. ]
[10.   7.5  8. ]
[8.7 4.  5. ]
[6.5 4.3 7.  1.5]
[ 0.   9.  10.   7.5  8.   8.7]
[4. 5.]


In [7]:
tabla = np.array([[6,7,8,9],
                  [5,7,9,1],
                  [2,4,6,8],
                  [0,7,5,3]
                  ])

## vsplit y hsplit: vsplit separa en filas y hsplit separa en columnas.

In [ ]:
# 2 parejas de alumnos dos clases, vsplit

print('VSPLIT en la vertical')
clase_a, clase_b = np.vsplit(tabla,2)
print(clase_a)
print('-'* 30)
print(clase_b)

print("#" * 30)

# 2 asignaturas por bloque

print('HSPLIT en la horizontal')
asignatura_a, asignatura_b = np.hsplit(tabla,2)
print(asignatura_a)
print('-'* 30)
print(asignatura_b)

VSPLIT en la vertical
[[6 7 8 9]
 [5 7 9 1]]
------------------------------
[[2 4 6 8]
 [0 7 5 3]]
##############################
HSPLIT en la horizontal
[[6 7]
 [5 7]
 [2 4]
 [0 7]]
------------------------------
[[8 9]
 [9 1]
 [6 8]
 [5 3]]


## Ordenación: np.sort y np.argsort

np.sort: ordena los valores
Ordena el valor de los elementos 

```
Datos:   [7, 2, 9, 1, 5, 3]
Ordenado:[1, 2, 3, 5, 7, 9]  ← de menor a mayor
```
np.argsort: ordena los indices

No devuelve los valores ordenados, sino **las posiciones** donde estarían en orden. Es muy útil cuando tienes dos arrays relacionados (p.ej. nombres y notas) y quieres ordenar uno según el otro.

```
Datos:    [7,  2,  9,  1,  5,  3]
Posición:  0   1   2   3   4   5

argsort:  [3,  1,  5,  4,  0,  2]
           ↑   ↑   ↑   ↑   ↑   ↑
         pos  pos pos pos pos pos
          del  del del del del del
          más pequeño          más grande
```

In [19]:
nombres = np.array(['Ana', 'Luis', 'Juan', 'Carlos', 'Marta', 'Pedro'])
notas = np.array([7.2, 6.1, 8.8 ,5.5 , 2.0, 7.5])

print('Datos originales')
for n, nota in zip(nombres, notas):
    print(f"{n:9s}:{nota}")

Datos originales
Ana      :7.2
Luis     :6.1
Juan     :8.8
Carlos   :5.5
Marta    :2.0
Pedro    :7.5


In [23]:
# np.sort: solo ordena las notas

notas_ordenadas_desc = np.sort(notas, descending=False)

print(notas_ordenadas_desc)

[2.  5.5 6.1 7.2 7.5 8.8]


In [ ]:
# quiero ordenar el array de nombres en funcion del orden notas. argsort
# quiero el ranking de peor a mejor nota

orden = np.argsort(notas)
print(nombres)
print(orden)

for o, alumnos in zip(orden, nombres):
    print( nombres[o] )
    
    
for ranking, value in enumerate(orden, start=1):
    print( f"{ranking}º - {nombres[value]}: {notas[value]}")




['Ana' 'Luis' 'Juan' 'Carlos' 'Marta' 'Pedro']
[4 3 1 0 5 2]
Marta
Carlos
Luis
Ana
Pedro
Juan
1º - Marta: 2.0
2º - Carlos: 5.5
3º - Luis: 6.1
4º - Ana: 7.2
5º - Pedro: 7.5
6º - Juan: 8.8


## Valores únicos: np.unique

Devuelve los valores que aparecen en el array eliminando los repetios, y tambien me dice cuantas veces se repita cada valor

In [74]:
# Ejemplo: respuestas a una encuesta de satisfacción (1 a 5 estrellas)
respuestas = np.array([3, 2, 1, 2, 2, 5, 3, 2, 3, 5, 2, 4])

# valores unicos
print(np.unique(respuestas))

# frecuencia de cada valor
puntuacion, conteo = np.unique(respuestas, return_counts=True)

indices_ordenados = np.argsort(conteo, descending=True)

print('Resultado de mi encuesta: ')
# for p, c in zip(puntuacion, conteo):
#     barra = "★" * c
#     print( f"{p} estrella: {c} respuesta {barra}" )

for i in indices_ordenados:
    c = conteo[i]
    p = puntuacion[i]
    barra = "★" * c
    print( f"{p} estrella: {c} respuesta {barra}" )

[1 2 3 4 5]
Resultado de mi encuesta: 
2 estrella: 5 respuesta ★★★★★
3 estrella: 3 respuesta ★★★
5 estrella: 2 respuesta ★★
1 estrella: 1 respuesta ★
4 estrella: 1 respuesta ★


---
**Resumen del tema:**

| Operación | Función | Qué hace |
|-----------|---------|----------|
| Unir en serie | `np.concatenate([a, b])` | Pega arrays uno tras otro |
| Apilar filas | `np.vstack([a, b])` | Pone b debajo de a (añade filas) |
| Apilar columnas | `np.hstack([a, b])` | Pone b a la derecha de a (añade columnas) |
| Dividir en N partes | `np.split(a, N)` | Divide en N partes iguales |
| Dividir en posiciones | `np.split(a, [i, j])` | Cortes en índices i y j |
| Dividir por filas | `np.vsplit(a, N)` | Parte la tabla horizontalmente |
| Dividir por columnas | `np.hsplit(a, N)` | Parte la tabla verticalmente |
| Ordenar valores | `np.sort(a)` | Devuelve copia ordenada |
| Índices de orden | `np.argsort(a)` | Devuelve posiciones para ordenar |
| Eliminar repetidos | `np.unique(a)` | Valores distintos (+ conteo opcional) |